### ISSUE TITLE
Marketplace product description can't display emoji

### ISSUE THREAD

**Issue by translate3d** [streamr-dev/core-frontend#1239]
**Describe the bug**
When creating a Streamr product I entered an emoji in the description field. After saving and publishing the product, the emoji was gone and 2 question marks were displayed.

**To Reproduce**
1. Go to 'Products'
2. Click on 'Create product'
3. Fill the form, enter an emoji into the description field
4. Publish
5. The emoji is gone

**Expected behavior**
Entered emojis should be visible.

**App version**
Open editor sidebar to see the app version [e.g. Streamr App v2.0.5-574-ga787e4e]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Mac
 - OS: MacOS 11.4
 - Browser: Brave
 - Version: 1.26.67

**Additional context**
It was a paid product, maybe that was the reason? Smart Contract etc.?

**Comment by fonty1** [comment]
Thanks for the well formed bug report! I have made a ticket for the backend team to take a look - I'm sure something is getting eaten in the encoding/decoding of the description.
