### ISSUE TITLE
DATA token points to etherscan

### ISSUE THREAD

**Issue by JiapengLi** [streamr-dev/core-frontend#1381]
https://streamr.network/docs/learn/data-tokenomics
DATA token points to https://etherscan.io/address/0x8f693ca8d21b157107184d29d398a8d082b38b76
Should it be replaced by polygon one?

**Comment by fonty1** [comment]
Thanks @JiapengLi - the token's basechain is Mainnet, though we should add Polygon as well. We'll be updating the docs over the coming weeks and we will address this.
