### ISSUE TITLE
Fix Link in README.md

### ISSUE THREAD

**Issue by 0xStuart** [streamr-dev/core-frontend#1736]
Fix link in README under Backend.  

Broken link.
https://github.com/streamr-dev/core-frontend/blob/master/here

**Comment by mondoreale** [comment]
@0xStuart thanks for reporting! Fixed in https://github.com/streamr-dev/core-frontend/commit/e8d2521fa35bcb7c6cd86a5bc5fd2dffce3e8680.

Have a great year, Sir!
