### ISSUE TITLE
 Problem with Metamask signature with Ledger Nano

### ISSUE THREAD

**Issue by einstanio** [streamr-dev/core-frontend#430]
When I try to register the eth address with metamask using the Ledger Nano hardware wallet, it returns an error.
![error](https://user-images.githubusercontent.com/25321685/57725925-95abab00-768e-11e9-8764-e6686c43f6c8.jpg)

**Comment by fonty1** [comment]
Good catch @einstanio, we haven't tested this out with the Ledger Nano and I was able to reproduce the bug.

I'll have a chat with our backend team about this tomorrow. A regular metamask Ethereum account will work if that's any help for now.

**Comment by fonty1** [comment]
After looking into it some more it appears to be a limitation with the `Ethers.js` library we use in our `streamr-client` stack. Unfortunately that leaves us stuck at the moment so we cannot add this functionality at this time. 

We will keep a close eye on their development, there appears to be a work in progress here: https://github.com/ethers-io/ethers-ledger
which looks promising.
