### ISSUE TITLE
Double click to open modal and add nodes

### ISSUE THREAD

**Issue by remykonings** [streamr-dev/core-frontend#451]
Currently you can only get the modal to add nodes appear at the left side of the canvas.

I think it would be a great feature to be able to double click anywhere on the canvas in order to get the modal up on that spot. Especially when the ability to zoom is added.

This enhances the usability significantly when canvases get bigger with more nodes.

**Comment by fonty1** [comment]
Hey @remykonings, I'll pass on this feedback to our chief designer @mattatgit.

**Comment by mattatgit** [comment]
@remykonings Quick clarification, the Module panel is not a modal (modal = user is blocked from doing anything outside the focused window), it is just a floating window.

You can already move it anywhere you want to. 

We could possibly add double click to jump it somewhere else in the canvas, but that would be quite odd behaviour for a floating panel, so not entirely convinced this would be a good thing.

**Comment by remykonings** [comment]
Ah, you're right. It is indeed a floating window.

Perhaps it is more a personal preference yes. I'm used to a 3D modelling / parametric design program called Rhino and Grasshopper, where this issue came from. I thought it might be a good option when a canvas would become bigger.

![test 1](https://user-images.githubusercontent.com/6934783/58013191-62d23e80-7af6-11e9-8490-d36341217469.png)
![test 2](https://user-images.githubusercontent.com/6934783/58013192-62d23e80-7af6-11e9-93ad-d01a22f7b731.png)

**Comment by mattatgit** [comment]
@remykonings We'll definitely keep it in mind. It was a feature of the old editor. The new panel has a couple of modes (Browse and Search), and it might make sense for this to work when in Search (minimised panel) mode, that would replicate the old functionality. 

But if a user accidentally triggers it and then wonders where their Module panel went, that's less than ideal. So we'll keep it in mind, and see how others feel.
