### ISSUE TITLE
Map from canvas not showing up in Dashboard view

### ISSUE THREAD

**Issue by remykonings** [streamr-dev/core-frontend#506]
I have a map which shows the cars location in a canvas. Thought it seems that it will not load that map in the dashboard view.

Streamr App version:
V.2.0.5. BETA

MacOS
Brave
Version 0.64.76 Chromium: 74.0.3729.157 (Official Build) (64-bit)

![Screen Shot 2019-05-31 at 13 27 30](https://user-images.githubusercontent.com/6934783/58703673-adcb3c00-83a9-11e9-98b1-33ea7c19aa48.png)
![Screen Shot 2019-05-31 at 13 27 40](https://user-images.githubusercontent.com/6934783/58703675-adcb3c00-83a9-11e9-8652-857f7ff4b8ac.png)

**Comment by fonty1** [comment]
@remykonings I can replicate this, good catch, I'll add this to our backlog and let you know when it's resolved 👍
