### ISSUE TITLE
Dashboard error

### ISSUE THREAD

**Issue by remykonings** [streamr-dev/core-frontend#609]
My dashboard shows an error about one second after i open it. This also means that i can not delete the dashboard in time.

Perhaps it is related to the issue on the map from the canvas which does not show up on the Dashboard as well. 

![Screen Shot 2019-07-30 at 23 52 04](https://user-images.githubusercontent.com/6934783/62168130-20fb1b00-b325-11e9-914c-5b618a5a6658.png)

![Screen Shot 2019-07-30 at 23 52 15](https://user-images.githubusercontent.com/6934783/62168143-28babf80-b325-11e9-96fa-0140eeb79d90.png)

![Screen Shot 2019-07-30 at 23 52 24](https://user-images.githubusercontent.com/6934783/62168150-2bb5b000-b325-11e9-81f9-26d4a0c8c965.png)

**App version**
Streamr App v2.0.5 BETA

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Safari
 - Version: 12.1.2 (13607.3.10)

**Comment by remykonings** [comment]
It indeed seems to be something related to the map as i can not add it to a new dashboard. It will also results in the same error.

**Comment by self-coding-crab** [comment]
Hi @remykonings 
I can handle this issue.
